<li class="control doddle-control">

    <?php if($moreInformation = $this->getMoreInformation()): ?>
        <div class="doddle-billing-more-information">
            <?php echo $moreInformation; ?>
        </div>
    <?php endif; ?>

    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_doddle" value="doddle" title="Collect From Doddle" class="radio" />
    <label for="billing:use_for_doddle"><span class="ship-to"><?php echo $this->__('Collect From'); ?></span> <img src="<?php echo $this->getSkinUrl('images/gene/doddle/logo.png'); ?>" class="doddle-logo" /></label>
</li>