<?php
/* @var $this Gene_Doddle_Block_Onepage_Shipping_Method_Doddle */

/** @var $helper Gene_Doddle_Helper_Data */
$helper = $this->helper('gene_doddle');
?>

<?php if ($this->onlyDoddle()): ?>
    <div style="display: none;">
        <input name="shipping_method" type="radio" value="<?php echo Mage::helper('gene_doddle')->getShippingMethodCode(); ?>" id="s_method_<?php echo Mage::helper('gene_doddle')->getShippingMethodCode(); ?>" checked="checked" class="radio" />
    </div>
<?php endif; ?>

<div id="doddle-box"<?php echo (!$this->onlyDoddle() ? ' style="display: none;"' : ''); ?>>
</div>

<script type="text/javascript">
    var emailAddress = '<?php echo $this->escapeHtml($this->getCustomerEmail()) ?>';
    var emailInputId = emailAddress.length ? null : 'billing:email';

    LocationFinder.init({
        root: 'doddle-box',
        apiKey: '<?php echo $helper->getApiKey() ?>',
        apiSecret: '<?php echo $helper->getApiSecret() ?>',
        googleApiKey: '<?php echo $helper->getGoogleApiKey() ?>',
        emailAddress: emailAddress,
        emailInputId: emailInputId,
        merchantId: '<?php echo $helper->getMerchantId() ?>',
        callback: cb
    });

    /**
     * This is called when a location is selected in the AusPost widget
     *
     * @param data
     */
    function cb(data) {
        if (data.storeId) {
            // Remove existing store ID from form
            if ($('doddle-store-selection')) {
                $('doddle-store-selection').remove();
            }
            // Add selected store ID to form
            $(shippingMethod.form).insert({
                bottom: new Element('input', {
                    id: 'doddle-store-selection',
                    type: 'hidden',
                    name: 'doddle-store',
                    value: data.storeId
                })
            });
            shippingMethod.save();
        }
    }

    // Observe shipping method choices
    doddle.observeShippingMethods();

    <?php if ($this->onlyDoddle()): ?>
    if ($('shipping-progress-opcheckout') != undefined) {
        $('shipping-progress-opcheckout').hide();
    }
    <?php endif; ?>

    // Add our new validation type
    Validation.add('validate-doddle', '<?php echo $this->__('Please select your Doddle collection store to continue.'); ?>', function(v) {
        // Check to see whether a method has been selected
        if($$('[name=doddle-store]:checked').first() == undefined) {
            doddle.throwError('<?php echo $this->__('Please select your Doddle collection store to continue.'); ?>');
            return false;
        }
        return true;
    });
</script>